[theme]
base = "light"
primaryColor = "#087F77"
backgroundColor = "#F8FAFC"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#101828"
font = "sans serif"

[client]
toolbarMode = "minimal"

[server]
maxUploadSize = 200
